title: JDoro.out.print(blog)
author: JDoro
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-remote-theme
baseurl: /jdoro-blog
