title: JDoro.out.print(blog)
author:
    name: Josh Doro
    email: "josh.j.doro@gmail.com"
plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-redirect-from
    - jekyll-archives
    - jekyll-remote-theme
    - jekyll-gist
    - jekyll-avatar
    - jekyll-include-cache
    - jekyll-optional-front-matter
    - jekyll-default-layout
    - jekyll-readme-index
remote_theme: jekyll/minima
baseurl: /jdoro-blog
minima:
    skin: solarized
    social_links:
        - { platform: github,  user_url: "https://github.com/JDoro" }
