title: JDoro.out.print(blog)
author:
    name: Josh Doro
    email: "josh.j.doro@gmail.com"
remote_theme: jekyll/minima
baseurl: /jdoro-blog
minima:
    skin: solarized
    social_links:
        - { platform: github,  user_url: "https://github.com/JDoro" }
